// <auto-generated />
using System;
using CompanySystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanySystem.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305115751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanySystem.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Appliances"
                        });
                });

            modelBuilder.Entity("CompanySystem.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 8,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ultra HD Smart TV with HDR and built-in streaming apps",
                            Price = 9500m,
                            Title = "Samsung 55\" 4K Smart TV"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 15,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless earbuds with noise cancellation",
                            Price = 7200m,
                            Title = "Apple AirPods Pro"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Count = 40,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Instant coffee made from premium roasted beans",
                            ExpiryDate = new DateOnly(2027, 1, 10),
                            Price = 180m,
                            Title = "Nescafe Classic Coffee 200g"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Count = 50,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh full-cream milk rich in calcium",
                            ExpiryDate = new DateOnly(2026, 3, 20),
                            Price = 35m,
                            Title = "Almarai Fresh Milk 1L"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Count = 6,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Digital microwave oven with grill function",
                            Price = 4200m,
                            Title = "LG Microwave Oven 25L"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Count = 9,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Healthy air fryer with rapid air technology",
                            Price = 3900m,
                            Title = "Philips Air Fryer"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Count = 33,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crunchy chocolate biscuits with cream filling",
                            ExpiryDate = new DateOnly(2026, 9, 15),
                            Price = 12m,
                            Title = "Oreo Chocolate Biscuits"
                        });
                });

            modelBuilder.Entity("CompanySystem.DAL.Product", b =>
                {
                    b.HasOne("CompanySystem.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CompanySystem.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
